import type { CascadeSettings, StatusDef } from "./schema";

export const ESSENTIAL_STATUSES: StatusDef[] = [
  { symbol: " ", label: "Open", icon: "□", essential: true },
  { symbol: "/", label: "In progress", icon: "◐", essential: true },
  { symbol: "x", label: "Done", icon: "✓", essential: true },
  { symbol: "-", label: "Cancelled", icon: "×", essential: true },
  { symbol: ">", label: "Migrated", icon: "→", essential: true },
  { symbol: "<", label: "Scheduled", icon: "←", essential: true },
];

export const DEFAULT_SETTINGS: CascadeSettings = {
  language: "auto",
  agendaRoot: "01-AGENDA",
  openTodayOnStartup: true,
  runMigrationOnStartup: true,
  runNormalizerOnStartup: true,
  startupDelaySeconds: 5,
  startupWaitCondition: "fixed",
  startupWaitMaxSeconds: 30,
  startupVaultIdleSeconds: 3,
  dailyEnabled: true,
  weeklyEnabled: true,
  monthlyEnabled: true,
  yearlyEnabled: true,
  operationalYearStartMonth: 1,
  dailyFormat: "YYYYMMdd0000-DDD",
  weeklyFormat: "YYYYWW0000-[W]WW",
  monthlyFormat: "YYYYMM000000-MMM",
  yearlyFormat: "YYYY00000000-YYYY",
  noteFormat: "YYYYMMddHHmm-SLUG",
  normalizerEnabled: true,
  normalizerUppercase: true,
  normalizerAccents: true,
  normalizerTimestamp: true,
  normalizerScopes: ["01-AGENDA"],
  normalizerIgnored: ["02-ARQUIVO/OBSIDIAN/TEMPLATES"],
  templatesFolder: "",
  dailyTemplate: "",
  weeklyTemplate: "",
  monthlyTemplate: "",
  yearlyTemplate: "",
  folderTemplates: [],
  recurringTasksPath: "02-ARQUIVO/TAREFAS/202606101111-01-RECORRENTES.md",
  taskGlobalFilter: "#tasks",
  taskSetCreatedDate: false,
  taskSetDoneDate: false,
  migrationEnabled: true,
  cancelExpiredScheduled: true,
  essentialStatuses: ESSENTIAL_STATUSES,
  customStatuses: [],
  calendarFirstDayOfWeek: 0,
  calendarShowWeekNumbers: false,
  calendarOpenInNewLeaf: false,
  calendarConfirmCreate: true,
  frontmatterEnabled: true,
  frontmatterCreatedKey: "created",
  frontmatterUpdatedKey: "updated",
  frontmatterDateFormat: "yyyy-MM-dd'T'HH:mm",
  frontmatterIgnoredPaths: [],
};

export function mergeSettings(data: Partial<CascadeSettings> | null | undefined): CascadeSettings {
  return {
    ...DEFAULT_SETTINGS,
    ...(data ?? {}),
    essentialStatuses: ESSENTIAL_STATUSES,
    customStatuses: data?.customStatuses ?? [],
    normalizerScopes: data?.normalizerScopes ?? DEFAULT_SETTINGS.normalizerScopes,
    normalizerIgnored: data?.normalizerIgnored ?? DEFAULT_SETTINGS.normalizerIgnored,
    folderTemplates: data?.folderTemplates ?? [],
    frontmatterIgnoredPaths: data?.frontmatterIgnoredPaths ?? [],
  };
}
